### ISSUE TITLE
Margin should not be shown in Mint

### ISSUE THREAD

**Issue by pkmnct** [pkmnct/robinhood-mint-sync-chrome#11]
A user that has margin trading with Robinhood Gold has reported that the margin is showing up in their portfolio balance.

**Comment by mromarreyes** [comment]
I would also like to have a setting that I can enable to not include margin.

**Comment by mwanninger** [comment]
+1 to this request. Thanks for the plugin!

**Comment by pkmnct** [comment]
@mromarreyes @mwanninger Could you check if version 3.0.0 displays the margin as expected?

**Comment by mwanninger** [comment]
@pkmnct I just checked it out - I removed my old "Robinhood Account" as prompted, then ran setup. It created 4 different property entries on Mint (Robinhood Cash, Robinhood Crypto, Robinhood Other, Robinhood Stocks), but appeared to get stuck after that. I refreshed and watched more closely, and it appears to go to Robinhood, then back to Mint, and then get stuck there and the tab doesn't close (it doesn't fill out or save any of the values either, all 4 property entries are still set to 0... some of that is expected as I don't have Robinhood Cash, Crypto, or Other (I don't think), just stocks).

Also, just want to clarify on the functionality requested here - margin is not counted towards your net worth (it's borrowed money, as you may know), so having it display in Mint as a positive value would be counter-intuitive and inflate your actual net worth. I think what the ask here, would be to either subtract margin from the "total market value" of the Robinhood account and add that in Mint, or just take the "Equity" value on Robinhood (that already subtracts margin) and have that be added to Mint. But open to other suggestions - my primary usage is not that I want to see my margin in Mint, but rather to have an accurate reflection of Net Worth there, which for me would just be the "Equity" value on my robinhood.com/account page.

Thanks so much again for the plug-in! Let me know if there are any other details I can send over that might help in figuring out why it doesn't seem to finish the sync.

**Comment by pkmnct** [comment]
@mwanninger Thanks for the clarification. I don't have a Robinhood Gold account to test with, but I was able to switch the API from using "market value" to "equity," which I hope will resolve the issue (in #24). I'm going to do a bit more testing before releasing.

**Comment by mwanninger** [comment]
@pkmnct Thanks! Let me know if I can be of any help since I do have/use Gold.

**Comment by pkmnct** [comment]
@mwanninger It'd be great if you're willing to test the changes. Do you have any familiarity with npm? If so, you can follow the [_Developer Use_](https://github.com/pkmnct/robinhood-mint-sync-chrome#developer-use) section of the guide with this zip: https://github.com/pkmnct/robinhood-mint-sync-chrome/archive/use-equity-not-market-value.zip

If not, I can make a zip of the compiled code for you to try.

Make sure to disable the main extension before loading the unpacked version.

**Comment by pkmnct** [comment]
Here is a complied version of the extension. You can load it directly for testing.
[robinhood-mint-sync-chrome-beta.zip](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5825557/robinhood-mint-sync-chrome-beta.zip)

1. Disable the main install of Robinhood Mint Sync.
2. Extract the attached zip to a folder.
3. Open the Chrome Extensions Page (Chrome Menu > More Tools > Extensions).
4. Turn on the Developer Mode switch on the top-right of the page.
5. Choose the _Load unpacked_ button and navigate to the folder you extracted to.

**Comment by mwanninger** [comment]
@pkmnct I just tried it - as with the live store version, the sync appears to fail so i can't check this for sure yet. In looking at the window that gets opened, it navigates to Robinhood, back to Mint, and then stays there.

Looking at the page (/settings.event on mint.com) behind the "Syncing Mint and Robinhood" overlay, it appears to have set my "Robinhood Stocks" value to the value I expect (no margin), but then "Robinhood Crypto" is expanded... so maybe it's getting stuck there? I don't have any crypto in my Robinhood right now (just taking a guess though).

**Comment by pkmnct** [comment]
Sounds like you are running into #22. I'll take a look at this again once that issue is resolved.

**Comment by pkmnct** [comment]
@mwanninger #22 has been fixed. Try this version instead, and let me know if it syncs the expected amounts:

[robinhood-mint-sync-chrome@3.2.1.zip](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5826933/robinhood-mint-sync-chrome%403.2.1.zip)

**Comment by mwanninger** [comment]
@pkmnct looks good! "Robinhood Stocks" amount is exactly what I expect
