### ISSUE TITLE
Net worth history in Mint shows a jump when Robinhood is added?

### ISSUE THREAD

**Issue by bluekeybo** [pkmnct/robinhood-mint-sync-chrome#12]
Can the extension get the history of the Robinhood account too? That way the Mint net worth tracker doesn't show jumps when Robinhood is added, or if I don't sync Robinhood with Mint after a few months and then I re-sync?
Thanks!

**Comment by pkmnct** [comment]
Unfortunately there is no Mint interface or API to manually add history for an account (besides transactions). Unless Mint adds functionality I don't believe this would be possible with the extension.
