### ISSUE TITLE
Balance only includes securities, but not cash.

### ISSUE THREAD

**Issue by forcey** [pkmnct/robinhood-mint-sync-chrome#13]
My portfolio includes $3600 in securities and $2000 in cash, but in the mint account only the $3600 is shown. Screenshots below.

<img width="324" alt="Screen Shot 2020-12-17 at 2 57 27 PM" src="https://user-images.githubusercontent.com/4744406/102553761-3edf3200-4078-11eb-8711-8ac4ed2b9eaf.png">
<img width="784" alt="Screen Shot 2020-12-17 at 2 57 23 PM" src="https://user-images.githubusercontent.com/4744406/102553768-40a8f580-4078-11eb-9e26-07320a8d555e.png">

**Comment by pkmnct** [comment]
Thanks for the report! I'm working to revamp the way the Robinhood portfolio is scraped, and am hopeful it will resolve this issue (among some others). It will be using the Robinhood API rather than scraping it from a page.

**Comment by billvsd** [comment]
+1 for adding the Robinhood Cash Management balance ([https://robinhood.com/cash](https://robinhood.com/cash)) - that would be very helpful whether by the current scraping method or via the API.
