### ISSUE TITLE
Sync Runs, accounts accessed yet the balance does not update

### ISSUE THREAD

**Issue by jakreymyers** [pkmnct/robinhood-mint-sync-chrome#15]
When I enabled the extension and clicked on the sync, it originally notified me that I did not have a Robinhood account setup. This was not the case, I did have an account but clicked "setup Robinhood account" and it thereafter seemed to realize that I did in fact have the account (maybe not?). However, I have run the sync several times and the values are not updating at all. It still says last updated was 2 months ago and there doesn't seem to be any exchange of info back into Mint from Robinhood.

**Comment by pkmnct** [comment]
@jakreymyers The extension is unable to access your existing Robinhood account within Mint as Mint does not offer any public-facing way to manually or programmatically adjust natively-connected accounts. What the extension does instead is creates a "Collectible" in Mint that it then updates with your portfolio value.

If that collectible does not appear in your account, feel free to re-open this issue as a bug.
