### ISSUE TITLE
The sync hangs after it returns to Mint with the black splash screen

### ISSUE THREAD

**Issue by minihadroncollider** [pkmnct/robinhood-mint-sync-chrome#2]
I start the sync and a tab is opened in Mint which then moves to Robinhood and back to Mint. It never completes this last step and just hangs there with the text "Syncing Mint and Robinhood... This window will automatically close when the sync is complete".

**Comment by minihadroncollider** [comment]
Hi George,

Thanks for the quick reply.
I followed the link to the property page and I can confirm there is a
property called "Robinhood Account" there.

Dan

**Comment by minihadroncollider** [comment]
Also - it gets stuck on the Mint page, not Robinhood

**Comment by pkmnct** [comment]
Are you still experiencing this issue with the latest release?

**Comment by minihadroncollider** [comment]
Hi George.
I actually uninstalled the plug-in since I couldn't get it to work and
furthermore, Robinhood seemed to start supporting native sync with Mint (or
vice versa).
Dan
