### ISSUE TITLE
Setup Box Not Working

### ISSUE THREAD

**Issue by alexskim21** [pkmnct/robinhood-mint-sync-chrome#3]
The Setup box pops up on Mint but when I click on the the "Set Up" button nothing happens. It just continues to hover in the top right hand corner of my screen. I can click on the button any number of times but nothing happens.

**Comment by kuroshhashemi** [comment]
Same.  Also if I click close, nothing happens

**Comment by jonchui** [comment]
Me too. 

However, i just found out that mint includes Robinhood now! 

![image](https://user-images.githubusercontent.com/204868/53758920-33028b80-3e63-11e9-96a1-2a97324517a0.png)

**Comment by kuroshhashemi** [comment]
OH MY GOD SAY IT AINT SO 😭

**Comment by sfadoo98** [comment]
Having same problem

**Comment by raku-cat** [comment]
Also having this issue, I'm using chromium 75.0.3770.80
The robinhood option in mint has shown up for quite a while for me but i've yet for it to actually work, it's failed every time I try it.
