### ISSUE TITLE
Firefox Version

### ISSUE THREAD

**Issue by JeffResc** [pkmnct/robinhood-mint-sync-chrome#37]
Hello,

I think this extension is great! I daily drive Firefox instead of Chrome, so unfortunately it's not compatible with my day-to-day browser. If it's possible and already compatible, could you release a version of this for Firefox or possibly add it to the project roadmap?

Thank you for this great project,
Jeff

**Comment by pkmnct** [comment]
Good news! With some small tweaks, it looks like it works just fine on Firefox. I'll work on getting this released.

**Comment by pkmnct** [comment]
The Firefox version is pending review by Mozilla. If approved, it will be available from:
https://addons.mozilla.org/en-US/firefox/addon/robinhood-mint-sync/

**Comment by pkmnct** [comment]
The extension was approved. You should be able to install it on Firefox now. Please open a new issue if you run into any issues with it!
