### ISSUE TITLE
Robinhood stocks and cash appear under properties on mint

### ISSUE THREAD

**Issue by georgekerr** [pkmnct/robinhood-mint-sync-chrome#38]
Is there a way to have these under investments instead of properties?

**Comment by pkmnct** [comment]
Unfortunately, Mint offers no way of manually creating a manual item that appears under Investments. See [_How do I add a manual account in Mint?_](https://help.mint.com/General/888960251/How-do-I-add-a-manual-account-in-Mint.htm) for more details.
