### ISSUE TITLE
Cash balance is being incorrectly set as buying power

### ISSUE THREAD

**Issue by billvsd** [pkmnct/robinhood-mint-sync-chrome#44]
The "Robinhood Cash" balance is incorrectly being set as the Buying Power amount. For example, if you have a $50 cash balance in Robinhood (robinhood.com/cash) and $1,000 in buying power, the Chrome Extension is setting the "Robinhood Cash" account value at $1050 when it should be $50. Under the account menu, it may say $1,050 buying power, but the actual cash balance is $50.

**Comment by billvsd** [comment]
Screenshots for reference: 
<img width="251" alt="Mint-RobinhoodCashBalance" src="https://user-images.githubusercontent.com/2430297/105931584-4f33e680-6000-11eb-9755-32b4ec7581a9.png">
<img width="130" alt="RH-buyingPower" src="https://user-images.githubusercontent.com/2430297/105931590-4f33e680-6000-11eb-9f5b-bae551f38e91.png">
<img width="531" alt="RH-cash" src="https://user-images.githubusercontent.com/2430297/105931591-4fcc7d00-6000-11eb-98ab-3552cc550837.png">

**Comment by superpowered** [comment]
Hmmmm looks like they do provide us with this number under `cash_available_from_instant_deposits`. So we'd have to change the `cash = parseFloat(request.uninvested_cash);` -> ` cash = parseFloat(request.uninvested_cash) - parseFloat(request.cash_available_from_instant_deposits);`.
OR there is the `withdrawable_cash ` which seems to return the cash value without buying power, but I'm not as sure what other scenarios could affect said number.

**Comment by pkmnct** [comment]
@superpowered I believe there are some other cases where that number does not match up, such as just after a deposit occurs. I believe that subtracting `cash_available_from_instant_deposits` should be correct.

**Comment by pkmnct** [comment]
This change has been submitted to the Chrome Web Store and Firefox Add-on site.
