### ISSUE TITLE
I'd like to tip you

### ISSUE THREAD

**Issue by linuxs** [pkmnct/robinhood-mint-sync-chrome#9]
Really appreciated this extension, saved me a ton of headache trying to reconcile my mint account! What's the best way to provide payment? 💯 👍 

Ran into this issue after migrating to Webull and adding my APEX clearing account to Mint; needed to import the Robinhood transactions easier.

**Comment by pkmnct** [comment]
Glad to hear it is still getting use! I accept tips/donations via either [Patreon](https://www.patreon.com/pkmnct) or [PayPal](https://www.paypal.me/pkmnct).

Thanks for the consideration!
